import { ModalProvider } from "@/providers/modal-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import ToastContext from "@/context/ToastContext";
import { ThemeProvider } from "@/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToastContext />
          <ModalProvider />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
